### ISSUE TITLE
Investigate Bluetooth Pairing issues on Mac OS Ventura

### ISSUE THREAD

**Issue by craigastill** [jackson15j/zmk-config#19]
I've tried the reset firmware mentioned in:

- https://github.com/zmkfirmware/zmk/issues/278
- https://zmk.dev/docs/troubleshooting/#split-keyboard-halves-unable-to-pair

The above fixed my connection to my IPhone, but is still broken with work
MacBook.

Need to try with USB logging and pull Mac console logs.

**NOTE:** Mac console log points to error code 708, which is a timeout code
apparently
(https://developer.apple.com/forums/thread/674642?answerId=663653022#663653022)

> These status codes are based on the Open Interface North America Bluetooth project. We cannot provide a preferred link to find this information, but doing a search for Open Interface North America status codes should yield useful results.
>
>Specifically to your question, Status 708 indicates a connection timeout. Status 719 means the remote side has closed the connection.
>
>You can see that these explanations of the status codes are also clearly printed in the logs you provided as CoreBluetooth errors.

**Comment by jackson15j** [comment]
Looks like this was fixed by latest Zephyr 3.2 changes that I merged in commit: 12a9154.

Marking as Closed.
